# fallback при старте
preload = /home/matehuslims/Pictures/wallpapers/wall1.jpeg
preload = /home/matehuslims/Pictures/wallpapers/wall2.jpeg
preload = /home/matehuslims/Pictures/wallpapers/wall3.jpeg
preload = /home/matehuslims/Pictures/wallpapers/wall4.jpeg
preload = /home/matehuslims/Pictures/wallpapers/wall5.jpeg
preload = /home/matehuslims/Pictures/wallpapers/wall6.jpeg
preload = /home/matehuslims/Pictures/wallpapers/wall7.jpeg
preload = /home/matehuslims/Pictures/wallpapers/wall8.jpeg
preload = /home/matehuslims/Pictures/wallpapers/wall9.jpeg

wallpaper {
    monitor =
    path = /home/matehuslims/Pictures/wallpapers/wall1.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/matehuslims/Pictures/wallpapers/wall1.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = /home/matehuslims/Pictures/wallpapers/wall1.jpeg
    fit_mode = cover
}
