monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.pci-0000_03_00.6"
      }
    ]
    actions = {
      update-props = {
        api.acp.auto-port = true
      }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_output.usb-TempoTec.*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 1500
        node.description = "M3 Pro"
        node.nick = "M3 Pro"
      }
    }
  }
]
